--CREATE TABLE(GUEST)
CREATE TABLE GUEST(
						GUEST_NO		NUMBER(10),
						GUEST_NAME		VARCHAR2(10),
						GUEST_DATE		DATE,
						GUEST_EMAIL		VARCHAR2(50),
						GUEST_HOMEPAGE	VARCHAR2(50),
						GUEST_TITLE		VARCHAR2(100),
						GUEST_CONTENT	VARCHAR2(4000)
					);

--CREATE SEQUENCE(GUEST)
CREATE SEQUENCE GUEST_NO_SEQ
INCREMENT BY 1
START WITH 0
NOMAXVALUE
MINVALUE 0
NOCYCLE
NOCACHE;


SELECT * FROM GUEST;